/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Answers: typeof import('./src/components/game/Answers.vue')['default']
    Aside: typeof import('./src/components/game/Aside.vue')['default']
    AsideItem: typeof import('./src/components/game/AsideItem.vue')['default']
    CarbonHelp: typeof import('~icons/carbon/help')['default']
    CarbonQuestion: typeof import('~icons/carbon/question')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    GameEnds: typeof import('./src/components/modal/GameEnds.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Help: typeof import('./src/components/game/Help.vue')['default']
    Index: typeof import('./src/components/game/Index.vue')['default']
    Item: typeof import('./src/components/thematics/Item.vue')['default']
    MdiClose: typeof import('~icons/mdi/close')['default']
    Rules: typeof import('./src/components/modal/Rules.vue')['default']
    ThematicsBack: typeof import('./src/components/modal/ThematicsBack.vue')['default']
  }
}
